USE RetailPOS;
GO

--Objects Users
INSERT INTO Users VALUES('root', '12345', 1, NULL)
INSERT INTO Users VALUES('administrador', '12345', 1, 1)
INSERT INTO Users VALUES('fernando.colque', '12345', 1, 2)

--Objects Images
INSERT INTO Images VALUES('Sale', 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABZ0RVh0VGl0bGUATGFiZWxzO0NoYXJ0O1BpZXSjLbQAAADWSURBVHheldI/CsJAEMXhAXtL/3SeJp2n8ACiggeQgE22VVsbLS1s7BW2EE8iSCAHGN8KA+Gxu8HiK99vCBtZn/c1eHBQgBhV/SnL0igLAW1poILhbHeKDkLQcMBcMe5PN7exXbZBKsDjAcZPqMKYKJPEWKGBwq6lSGJsXGeAx8TzNzOhMat5yEHBYAuaCeRfYXM4jjC4JAK+80d631evTMS1A+3rFpbPY6kc+esZQyARqSIXlVmAI3OYxAIctIBpEFkg0kMgcjEeqMGDgwIEEUEkBJiyL7yghmw8L6vkAAAAAElFTkSuQmCC')
INSERT INTO Images VALUES('Calendar', 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABt0RVh0VGl0bGUATW9udGggVmlldztNb250aDtWaWV3RE7GVwAAAFRJREFUeF7NksEJwEAIBLfBtJFCgkWluzkuKEheJnJwj2HxsQOiMjM67CPQH9YIjusmcQKa6XNJ8OBFIrsClQWA3isA3wS5tFhQvwJBFmz0SB0EPQZVHisF1M3+LAAAAABJRU5ErkJggg==')
INSERT INTO Images VALUES('Inventory', 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABx0RVh0VGl0bGUAUGFja2FnZTtQcm9kdWN0O0dyb3VwO56BdyIAAABNSURBVHhe3c8xCgAgCIVhz9wZu0s01Nj6EsrlLYESQcM3hPBr0nMy8IgHgEUfHnBvtkg0gHgA8OELBqmqbI3nxy/wNp7fD7C/A/I+MAF9mP0RDet/9wAAAABJRU5ErkJggg==')
INSERT INTO Images VALUES('Configuration', 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAACt0RVh0VGl0bGUAU2V0dXA7Q3VzdG9taXo7RGVzaWduO1NldHRpbmc7UHJvcGVydDgftSEAAACfSURBVHhepZMxCkMhEERzjI/Y2tjIHiRnElJ6lJwgF/q99W82E5gfhmAIYYtXuDM74K5e3H3J9fYoYJLyzacNG0hybsBJk3oC23nWZgd3YCCDAQ4yWDN6/AzRVAq/oTd9XsH+CLDVDLIYdtBBJZ01J/kdwGk3MMTQF1vpog/2lJcwKRxiqIuASk29MxwQvkJoiPE1xh9S/CnHP1P4Oz8BxElwF15K2DcAAAAASUVORK5CYII=')
INSERT INTO Images VALUES('Class', 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAotJREFUOI2FkUtIVHEUxr9z71znpUPO+BgtqxkEIYvAiVpkIbSQVGwVI9RC2mlk0IOIiohMCaPAx6JFBBWIlYZkKpjmQgIXlRko+aTISS1tHJ/33pn/aeFrTIe+7fl+3/n+508Ik3u7DfXlueS0W6oByIF5rch7o4V7Bn4jkuQNcFkunA5LFREVE5HHqMiJ+Znu5q5eH8anFiIHuJNtqC/PgdNhfUBE51aHRHTAqMhx+Znulvp3Q5hb1DcFGJbh43A6rPeI6Py/BiIU2yxKbXys+f3PqQUcTc3GkdRsm6ovBZ50V0NurzyBpLjou0TSpS0ashB8YWZWfVn54jM8O44hb593l0kxdVuiouP3Jmd0kO/1mTuSJF3dguXxgHT564R8v6t/Dj98KjzmrBRFN3cSkWvZwbcMRJS6GQU6Box4P6JUAKigKBPtTFGYfskgIgqz7pFULXSKmV+F8yHB12aXSCYi0nVdjgnEO5Im0gaVkJHWl3AjszgtFZa2BVU9VMDMjSuDm/OLWnn/twAAwO//A8u0fZaE1Ld+GG4SQnjrPjzSpc6PYyi83aarWsjLzCcD81qp93oLhsZm1io97a4JBkN6AQtu0gmtg3bTlfaU6NCovIS1SukuO5LjrBj2zWBkLIDcvHy4XG4xOTkhPa+rRbrTg7ysEmUk1pQxbjM1M/AmpKmF4QfZoNUAVVUln28MMG3DoitnvyaZ3xKRAwCEEI8NkQKYGczsNxqNwuVyY5GsPCwZNvwCEfkjBkxPT8FqtdqJCCL5YMJk1O5eJjkhbEGNCGoXIz4hXIdKnkExx1QR0dkV+KEIasV9DWUs/w8GgJnvXxCXdrhVMiiJAHpEUCvqayhj/+gn/AXTDRpjVMTg1QAAAABJRU5ErkJggg==')
INSERT INTO Images VALUES('List', 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJ0RVh0VGl0bGUATGlzdDtCdWxsZXQ7UXN/OQAAAEhJREFUeF7t0MEJACAMA0AXdJfOIBnKcbpJLIKgH0Xrs4/rpxBCEkmXfnKpYtTIa4AaGh0PANw5NgCwNQcsvgXEiDHihT8buDQvIq+adzNO6AAAAABJRU5ErkJggg==')

--Objects Controls
INSERT INTO Controls VALUES('C01', 'GridControl', 1)
INSERT INTO Controls VALUES('C02', 'TreeView', 1)
INSERT INTO Controls VALUES('C03', 'PivotGriControl', 1)

--Objects Containers
INSERT INTO Containers VALUES(NULL, 4, NULL, 'C001', 'Configuration', 'Gestión de configuraciones', 0, NULL, 4, 0, 1, 1)
INSERT INTO Containers VALUES(NULL, 3, NULL, 'C002', 'Inventory', 'Gestión de inventarios', 0, NULL, 3, 0, 1, 1)
INSERT INTO Containers VALUES(NULL, 2, NULL, 'C003', 'Purchase', 'Gestión de compras', 0, NULL, 2, 0, 1, 1)
INSERT INTO Containers VALUES(NULL, 1, NULL, 'C004', 'Sales', 'Gestión de ventas', 0, NULL, 1, 0, 1, 1)
INSERT INTO Containers VALUES(1, NULL, NULL, 'C005', 'Security', 'Seguridad', 1, NULL, 2, 0, 1, 1)
INSERT INTO Containers VALUES(5, NULL, 1, 'C006', 'User', 'Usuarios', 2, 'FrmUser', 1, 1, 1, 1)
INSERT INTO Containers VALUES(1, NULL, NULL, 'C007', 'Configuration', 'Configuración', 1, NULL, 1, 0, 1, 1)
INSERT INTO Containers VALUES(7, NULL, 1, 'C008', 'Container', 'Contenedor', 1, 'FrmContainer', 1, 1, 1, 1)
INSERT INTO Containers VALUES(7, NULL, 1, 'C009', 'Coding', 'Codificación', 1, 'FrmCoding', 2, 1, 1, 1)

--Objects Consults
INSERT INTO Consults VALUES(6, 1, 'SELECT Id, Activo, Nombre, Contraseña, [Ultima modificación]', 'FROM eUsers', NULL, NULL, NULL, NULL, 1)
INSERT INTO Consults VALUES(8, 1, 'SELECT Id, Activo, [Contenedor padre], Codigo, Nombre, Descripcion, Nivel, Formulario, Orden, [Es vista], [Ultima modificación]', 'FROM eContainers', NULL, NULL, NULL, NULL, 1)
INSERT INTO Consults VALUES(9, 1, 'SELECT Id, Activo, Contenedor, Texto, Número, [Logitud número], [Ultima modificación]', 'FROM eCodings', NULL, NULL, NULL, NULL, 1)