//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coding
    {
        public int Id { get; set; }
        public string Entity { get; set; }
        public string Text { get; set; }
        public int Number { get; set; }
        public int NumberLength { get; set; }
        public bool Active { get; set; }
        public int IdUser { get; set; }
    }
}
