//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryOutputInput
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryOutputInput()
        {
            this.InventoryOutputInputItem = new HashSet<InventoryOutputInputItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public int IdDocument { get; set; }
        public int IdPerson { get; set; }
        public int IdBranchOffice { get; set; }
        public int IdWarehouse { get; set; }
        public string Number { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime BroadcastDate { get; set; }
        public System.DateTime Hour { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Discount { get; set; }
        public decimal Tax { get; set; }
        public decimal Total { get; set; }
        public bool Canceled { get; set; }
        public int IdUser { get; set; }
        public System.DateTime Starting { get; set; }
        public System.DateTime Ending { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Person Person { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryOutputInputItem> InventoryOutputInputItem { get; set; }
    }
}
