//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDocument
    {
        public int Id { get; set; }
        public int IdPersonDocumentType { get; set; }
        public int IdPerson { get; set; }
        public string Number { get; set; }
        public bool Principal { get; set; }
        public int IdUser { get; set; }
        public System.DateTime Starting { get; set; }
        public System.DateTime Ending { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual PersonDocumentType PersonDocumentType { get; set; }
    }
}
