//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductUnit()
        {
            this.ProductPrice = new HashSet<ProductPrice>();
            this.ProductUnitBarCode = new HashSet<ProductUnitBarCode>();
            this.PurchaseItem = new HashSet<PurchaseItem>();
            this.SalesItem = new HashSet<SalesItem>();
            this.InventoryOutputInputItem = new HashSet<InventoryOutputInputItem>();
        }
    
        public int Id { get; set; }
        public int IdProduct { get; set; }
        public int IdUnitTemplate { get; set; }
        public string Code { get; set; }
        public bool Sale { get; set; }
        public bool Purchase { get; set; }
        public bool Inventory { get; set; }
        public bool Reference { get; set; }
        public decimal Weight { get; set; }
        public decimal Volume { get; set; }
        public decimal Long { get; set; }
        public decimal Width { get; set; }
        public decimal High { get; set; }
        public bool Active { get; set; }
        public int IdUser { get; set; }
        public System.DateTime Starting { get; set; }
        public System.DateTime Ending { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPrice> ProductPrice { get; set; }
        public virtual UnitTemplate UnitTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductUnitBarCode> ProductUnitBarCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseItem> PurchaseItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesItem> SalesItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryOutputInputItem> InventoryOutputInputItem { get; set; }
    }
}
