//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasePaymentMethod
    {
        public int Id { get; set; }
        public int IdPurchase { get; set; }
        public int IdPaymentMethod { get; set; }
        public string Reference { get; set; }
        public decimal Total { get; set; }
        public int IdUser { get; set; }
        public System.DateTime Starting { get; set; }
        public System.DateTime Ending { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
