//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdConsult { get; set; }
        public string Condition { get; set; }
        public string ConditionDev { get; set; }
    
        public virtual Consult Consult { get; set; }
        public virtual User User { get; set; }
    }
}
